/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        surface: "var(--color-surface)",
        "on-primary": "var(--color-on-primary)",
        "error-container": "var(--color-error-container)",
        "primary-container": "var(--color-primary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-background": "var(--color-on-background)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary": "var(--color-on-tertiary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-bright": "var(--color-surface-bright)",
        "on-error-container": "var(--color-on-error-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary-container": "var(--color-on-primary-container)",
        tertiary: "var(--color-tertiary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-error": "var(--color-on-error)",
        background: "var(--color-background)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)",
        outline: "var(--color-outline)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-secondary": "var(--color-on-secondary)",
        error: "var(--color-error)",
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        "outline-variant": "var(--color-outline-variant)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "64px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "label-sm": ["Montserrat"],
        "headline-lg": ["Playfair Display"],
        "label-md": ["Montserrat"],
        "display-lg": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "body-md": ["Montserrat"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        // Missing from the client's own mockup config (docs/mockups/*.html) despite
        // being used in their markup (home.html L218/222/226/230, detalle L224).
        // Defined here to fix the gap rather than silently port the broken class.
        "label-sm-mobile": ["11px", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "500" }],
      },
      boxShadow: {
        // Promoted from a raw CSS class (catalogo.html L103: `.ambient-shadow`) and
        // an inline `style` (home.html L141, detalle-producto.html L150) into a
        // real Tailwind token so it's usable as `shadow-ambient`.
        ambient: "0px 10px 30px rgba(26, 26, 26, 0.05)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        fadeIn: "fadeIn 200ms ease-in-out",
      },
    },
  },
  plugins: [],
};
